### ISSUE TITLE
Option to filter links between devices via tags

### ISSUE THREAD

**Issue by bortok** [netreplica/nrx#57]
Even if two interconnected devices should be present in the exported topology, it is sometimes necessary to limit the list of connections between them to a certain subset. For example, in a multi-tenant setup, some links maybe dedicated for one customer, and other links to another. To filter a list of connections tags could be used.

Requestor: @frederic-loui

**Comment by bortok** [comment]
List of interfaces is extracted for each device individually: https://github.com/netreplica/nrx/blob/main/nrx/nrx.py#L191, and then each interface is checked for type (ethernet) and if it is connected. A check could be added for a supplied `tag`, to limit the export.

**Comment by frederic-loui** [comment]
Hi ! `1` seems to be more flexible. I have a question though while entering data into `nbx.rare.nmaas.eu`. While having to parse `tag` at `interface` and `cable` layer, would not it be preferable to use `circuit tag` in order to deal with tenancy export ? In that case we would have topology for `core` network but we would also have an other type for `customer/tenant` topology export ? As usual, we can have a quick VC if needed, as this use case applies to to what we would like to achieve. Depending on your choice we will follow your decision :-)
